spring.application.name=Eureka-Server
#Default if no post given id 8761 else can take any
server.port=8761
#Eureka server should not register as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false